import os
from pathlib import Path

def split_manual():
    # Path to the converted manual in the subfolder
    manual_path = Path("data/source_manual/PRINCE2_v7_manual.md")
    
    if not manual_path.exists():
        print(f"Error: {manual_path} not found. Ensure parser.py finished successfully.")
        return

    with open(manual_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Define the core split points for v7 structure
    # These match common Markdown header formats generated by Docling
    sections = {
        "principles": ["# Principles", "## Principles", "2 Principles"],
        "people": ["# People", "## People", "3 People"],
        "practices": ["# Practices", "## Practices", "4 Practices"],
        "processes": ["# Processes", "## Processes", "5 Processes"]
    }

    output_dir = Path("data/syllabus")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Search and extract sections
    content_lower = content.lower()
    for name, headers in sections.items():
        start_idx = -1
        for header in headers:
            start_idx = content.find(header)
            if start_idx != -1:
                break
        
        if start_idx != -1:
            # Find the start of the next major chapter to define the end of the chunk
            # PRINCE2 v7 manual chapters are usually numbered or use # Level 1 headers
            next_section_idx = content.find("\n# ", start_idx + 10)
            if next_section_idx == -1:
                chunk = content[start_idx:]
            else:
                chunk = content[start_idx:next_section_idx]
            
            output_file = output_dir / f"{name}.md"
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(chunk)
            print(f"Extracted: {output_file.relative_to(Path.cwd())}")
        else:
            print(f"Warning: Could not find header for {name}. Check the .md file for exact titles.")

if __name__ == "__main__":
    split_manual()
